import {
  Globe,
  Bot,
  TrendingUp,
  Mic,
  PenTool,
  Zap,
  BarChart3,
  MapPin,
  Building2,
  Stethoscope,
  GraduationCap,
  Home,
  Briefcase,
  ShoppingBag,
  UserCheck,
  Code2,
  Video,
  Layers,
  Sparkles,
  Search,
  CheckCircle2,
  PhoneCall,
  MessageSquare,
  DollarSign,
  type LucideIcon,
} from "lucide-react";

export type ServiceItem = {
  id: string;
  title: string;
  category: string;
  description: string;
  deliverables: string[];
  priceUSD: string;
  priceINR: string;
  badge?: string;
  isPopular?: boolean;
};

export type IndustryPackage = {
  id: string;
  industry: string;
  title: string;
  tagline: string;
  priceUSD: string;
  priceINR: string;
  period?: string;
  icon: LucideIcon;
  deliverables: string[];
  targetAudience: string;
  isFeatured?: boolean;
};

export type ServiceCategory = {
  id: string;
  name: string;
  shortDesc: string;
  icon: LucideIcon;
  itemCount: number;
};

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: "web-dev",
    name: "Web Development & Design",
    shortDesc: "High-performance Next.js websites, SaaS frontends, e-commerce & mobile web apps.",
    icon: Globe,
    itemCount: 20,
  },
  {
    id: "process-automation",
    name: "Process Automation & Integration",
    shortDesc: "Workflows, CRM sync, WhatsApp sequences, document extraction & RAG systems.",
    icon: Zap,
    itemCount: 21,
  },
  {
    id: "voice-audio",
    name: "Audio & Voice Production",
    shortDesc: "Voiceover production, IVR script systems, dubbing & regional voice setup.",
    icon: Mic,
    itemCount: 12,
  },
  {
    id: "content-copy",
    name: "Content & Conversion Copywriting",
    shortDesc: "High-converting website copy, SEO articles, video scripts & ghostwriting.",
    icon: PenTool,
    itemCount: 20,
  },
  {
    id: "marketing-growth",
    name: "Marketing & Growth Engineering",
    shortDesc: "Technical SEO, paid ads management, email drip sequences & CRO audits.",
    icon: TrendingUp,
    itemCount: 13,
  },
  {
    id: "industry-packages",
    name: "Turnkey Industry Packages",
    shortDesc: "Complete, done-for-you digital suites for Healthcare, Real Estate, E-com & SMBs.",
    icon: Layers,
    itemCount: 10,
  },
  {
    id: "data-research",
    name: "Data & Market Intelligence",
    shortDesc: "Competitor teardowns, market research reports, scraping & audience profiling.",
    icon: BarChart3,
    itemCount: 6,
  },
  {
    id: "india-localization",
    name: "India & Regional Market Solutions",
    shortDesc: "Vernacular ad copy in 6 languages, Razorpay optimization & Bharat landing pages.",
    icon: MapPin,
    itemCount: 6,
  },
  {
    id: "ai-agents",
    name: "Autonomous AI Agents",
    shortDesc: "24/7 Intelligent software agents for Sales, Support, Operations & Finance.",
    icon: Bot,
    itemCount: 10,
  },
];

/* ─── Turnkey Industry Packages ─────────────────────────────────────────── */
/* Realistic US agency market pricing vs domestic Indian business market pricing */

export const INDUSTRY_PACKAGES: IndustryPackage[] = [
  {
    id: "pkg-healthcare",
    industry: "Healthcare & Wellness",
    title: "Clinic & Healthcare Growth Suite",
    tagline: "Complete patient acquisition, 24/7 booking engine & reputation manager.",
    priceUSD: "$4,999",
    priceINR: "₹1,49,999",
    period: "One-time setup + 1 yr hosting",
    icon: Stethoscope,
    isFeatured: true,
    targetAudience: "Dermatology Clinics, Dental Surgeries, Physiotherapists, Specialty Hospitals & Wellness Centers",
    deliverables: [
      "Custom Next.js Clinic Website (Live in 7 days)",
      "24/7 WhatsApp Appointment Booking & Intake Automation",
      "Automated Post-Treatment Care & Medication Reminders",
      "Google Business Profile Local SEO & Ratings Booster",
      "Monthly Health Newsletter & Patient Education Pipeline",
      "WhatsApp Prescription Expiry & Re-booking Sequence",
    ],
  },
  {
    id: "pkg-real-estate",
    industry: "Real Estate & Housing",
    title: "Real Estate Lead Accelerator Suite",
    tagline: "High-converting listing portal, qualified lead funnels & automated broker messaging.",
    priceUSD: "$4,500",
    priceINR: "₹1,39,999",
    period: "One-time setup + portal build",
    icon: Home,
    isFeatured: true,
    targetAudience: "Real Estate Developers, Boutique Agencies, Property Brokers & Rental Managers",
    deliverables: [
      "High-Speed Property Listing Portal with Dynamic Filters",
      "Brochure Copywriting & Virtual Tour Script Packaging",
      "Automated Broker Lead Capture & WhatsApp Sequence",
      "Neighborhood Comparison & Investor Pitch Teardown Reports",
      "RERA-Compliant Terms & Contract Template Architecture",
      "CRM Webhook Integration (Zoho / HubSpot / Salesmate)",
    ],
  },
  {
    id: "pkg-education",
    industry: "Education & Coaching",
    title: "EduScale Coaching & Institute Suite",
    tagline: "Custom CBT testing engine, student portal, quiz generator & parent updates.",
    priceUSD: "$3,999",
    priceINR: "₹1,29,999",
    period: "One-time setup + platform license",
    icon: GraduationCap,
    isFeatured: true,
    targetAudience: "Coaching Institutes, Test Prep Academies (NEET/UPSC/JEE), Tutors & EdTech Founders",
    deliverables: [
      "White-Label CBT Computer-Based Testing Platform",
      "Automated MCQ & Quiz Generation Engine from Syllabus PDFs",
      "Student Performance Heatmap & Parent Progress Reporter",
      "Personalized Study Plan Generator for Enrolled Students",
      "Vernacular Content Translation into Regional Languages",
      "Institute Growth Landing Page & Free Trial Demo Flow",
    ],
  },
  {
    id: "pkg-ecommerce",
    industry: "E-Commerce & D2C",
    title: "E-Commerce Scale & Conversion Suite",
    tagline: "Custom store build, bulk product copy, cart recovery & ad variations engine.",
    priceUSD: "$5,999",
    priceINR: "₹1,89,999",
    period: "One-time build + automation setup",
    icon: ShoppingBag,
    isFeatured: true,
    targetAudience: "D2C Brands, Shopify Store Owners, Fashion Boutiques & Retail Exporters",
    deliverables: [
      "High-Conversion Custom Store Build (Shopify or Custom Next.js)",
      "Bulk Product Description Copywriting (CSV In / CSV Out)",
      "Automated WhatsApp Abandoned Cart & Post-Purchase Sequences",
      "Meta & Google Ad Copy Variation Generation Engine",
      "Automated Review & Testimonial Collection Pipeline",
      "Competitor Pricing Monitor & Inventory Alert Architecture",
    ],
  },
  {
    id: "pkg-saas",
    industry: "SaaS & Tech Startups",
    title: "SaaS MVP Launch & Growth Engine",
    tagline: "Production-ready web application, onboarding funnels & customer acquisition.",
    priceUSD: "$7,500",
    priceINR: "₹2,29,999",
    period: "One-time MVP build",
    icon: Code2,
    isFeatured: true,
    targetAudience: "Software Founders, Tech Agencies, Bootstrappers & Micro-SaaS Builders",
    deliverables: [
      "Full-Stack Next.js + Supabase SaaS MVP Development",
      "User Onboarding Email Sequence & Product Walkthrough",
      "Help Center & Knowledge Base Documentation Portal",
      "Automated Git-Commit Changelog & Release Notes Generator",
      "Cold Outreach B2B Campaign Setup for Early Signups",
      "Pricing Page A/B Testing & Micro-Copy Architecture",
    ],
  },
  {
    id: "pkg-local-smb",
    industry: "Local & SMB Businesses",
    title: "Local Business Dominance Package",
    tagline: "Mobile-first website, Google Maps dominance & automated review manager.",
    priceUSD: "$2,499",
    priceINR: "₹84,999",
    period: "One-time setup",
    icon: Building2,
    targetAudience: "Restaurants, Salons, Auto Garages, Local Retailers & Service Providers",
    deliverables: [
      "Custom Mobile-First 5-Page Business Website (Live in 7 days)",
      "Google Business Profile Optimization & Maps Top-3 Strategy",
      "Automated Customer Review Request Sequence via WhatsApp",
      "Digital Menu / Service Price List & FAQ Builder",
      "WhatsApp Business Catalog Copywriting & Setup",
    ],
  },
  {
    id: "pkg-legal-finance",
    industry: "Legal, CA & Financial Services",
    title: "Legal & CA Firm Practice Engine",
    tagline: "Client consultation portal, contract builders & financial report engines.",
    priceUSD: "$3,500",
    priceINR: "₹1,19,999",
    period: "One-time setup",
    icon: Briefcase,
    targetAudience: "Chartered Accountants, Law Firms, Tax Consultants & Financial Advisors",
    deliverables: [
      "Professional Executive Firm Website with Consultation Booking",
      "Plain-English Financial Summary Generator for Client Reports",
      "Contract & NDA Template Generator Architecture",
      "GST Compliance Document & Filing Checklist Workflows",
      "Automated Overdue Invoice Follow-up Email & SMS System",
    ],
  },
  {
    id: "pkg-hr-recruitment",
    industry: "HR & Talent Agencies",
    title: "HR & Recruitment Operations Suite",
    tagline: "Candidate shortlisting system, interview scheduler & employee onboarding.",
    priceUSD: "$3,999",
    priceINR: "₹1,24,999",
    period: "One-time setup",
    icon: UserCheck,
    targetAudience: "HR Agencies, Staffing Firms, Growing Companies & People Operations Teams",
    deliverables: [
      "Automated Candidate Shortlisting & Resume Analysis Engine",
      "Interview Scheduling & Calendar Synchronization System",
      "Role-Specific Job Description Writing & Copywriting Suite",
      "Employee Onboarding WhatsApp Workflow & Policy FAQ Portal",
      "Performance Review Summary & Exit Interview Generator",
    ],
  },
  {
    id: "pkg-creators",
    industry: "Creators & Media Studios",
    title: "Creator Engine & Monetization Suite",
    tagline: "High-speed creator site, video repurposing pipeline & course launch funnel.",
    priceUSD: "$2,499",
    priceINR: "₹79,999",
    period: "One-time setup",
    icon: Video,
    targetAudience: "Youtubers, Podcasters, Course Creators, Authors & Influencers",
    deliverables: [
      "Editorial Creator Portfolio & Digital Product Store",
      "Long-Form Video to Shorts/Reels Script Extraction Pipeline",
      "Podcast Audio to Show Notes & Timestamp Generator",
      "Course Launch Email Campaign & Lead Magnet Sequence",
      "YouTube Channel SEO & Thumbnail A/B Testing Copy",
    ],
  },
  {
    id: "pkg-agencies",
    industry: "Agencies & Consultants",
    title: "Agency White-Label & Scale Suite",
    tagline: "White-label content output, client pitch decks & automated client dashboards.",
    priceUSD: "$4,999",
    priceINR: "₹1,69,999",
    period: "One-time setup",
    icon: Sparkles,
    targetAudience: "Marketing Agencies, SEO Firms, Design Studios & Independent Consultants",
    deliverables: [
      "White-Label Copywriting & Content Fulfillment Pipeline",
      "Custom Client Audit Reports (SEO, Speed, Conversion)",
      "Automated Client Progress Dashboard (Looker Studio / Next.js)",
      "Client Proposal & Pitch Deck Narrative Generation Suite",
      "Cold Email Personalization Engine for Agency Outbound",
    ],
  },
];

/* ─── Individual Services Catalog (Categories 1-5, 7, 8) ──────────────────── */

export const ALL_SERVICES: ServiceItem[] = [
  /* ── 01: Web Development & Design ── */
  {
    id: "web-01",
    title: "Custom Website Design & Development",
    category: "web-dev",
    description: "Bespoke, high-performance web architecture built with Next.js & React.",
    deliverables: ["Next.js App", "Tailwind CSS", "SEO Infrastructure", "7-Day Delivery"],
    priceUSD: "$2,999 – $6,500",
    priceINR: "₹49,999 – ₹1,49,999",
    badge: "Popular",
    isPopular: true,
  },
  {
    id: "web-02",
    title: "High-Converting Landing Page Architecture",
    category: "web-dev",
    description: "Laser-focused landing pages engineered for maximum paid ad conversion rates.",
    deliverables: ["Conversion Architecture", "A/B Test Ready", "Sub-1s Load Time"],
    priceUSD: "$1,499 – $3,500",
    priceINR: "₹29,999 – ₹69,999",
  },
  {
    id: "web-03",
    title: "SaaS Product Frontend Engineering",
    category: "web-dev",
    description: "Scalable frontend components for SaaS web applications using React & Next.js.",
    deliverables: ["Component Library", "State Management", "API Hook Integration"],
    priceUSD: "$4,500 – $9,999",
    priceINR: "₹89,999 – ₹2,49,999",
  },
  {
    id: "web-04",
    title: "Full Web Application Development",
    category: "web-dev",
    description: "End-to-end web apps with authentication, database models & payment flows.",
    deliverables: ["Full-Stack App", "Database Setup", "Auth System", "Payment Gateway"],
    priceUSD: "$6,500 – $15,000",
    priceINR: "₹1,49,999 – ₹3,99,999",
  },
  {
    id: "web-05",
    title: "E-Commerce Store Setup & Engineering",
    category: "web-dev",
    description: "Custom Shopify or headless e-commerce builds tuned for mobile checkout.",
    deliverables: ["Product Catalog", "Cart Optimization", "Payment Gateway", "Inventory Sync"],
    priceUSD: "$3,500 – $8,500",
    priceINR: "₹69,999 – ₹1,89,999",
  },
  {
    id: "web-06",
    title: "Portfolio & Personal Brand Sites",
    category: "web-dev",
    description: "Editorial portfolios for creators, executives, founders & agencies.",
    deliverables: ["Custom Layout", "Fast Media CDN", "Contact Funnel"],
    priceUSD: "$1,999 – $4,200",
    priceINR: "₹39,999 – ₹89,999",
  },
  {
    id: "web-07",
    title: "Agency & Corporate Websites",
    category: "web-dev",
    description: "Multi-page corporate platforms with CMS integrations & lead funnels.",
    deliverables: ["Multi-page System", "CMS Integration", "Careers & Blog Module"],
    priceUSD: "$4,999 – $11,500",
    priceINR: "₹99,999 – ₹2,49,999",
  },
  {
    id: "web-08",
    title: "Mobile-Responsive Redesigns",
    category: "web-dev",
    description: "Modernizing clunky, legacy websites into slick mobile-first experiences.",
    deliverables: ["Mobile Optimization", "UX Audit Fixes", "Modern Styling"],
    priceUSD: "$1,499 – $3,500",
    priceINR: "₹29,999 – ₹69,999",
  },
  {
    id: "web-09",
    title: "Website Speed & Performance Optimization",
    category: "web-dev",
    description: "Core Web Vitals tuning, image compression & server-side caching setup.",
    deliverables: ["90+ Lighthouse Score", "CDN Setup", "Bundle Shrinking"],
    priceUSD: "$899 – $1,999",
    priceINR: "₹14,999 – ₹39,999",
  },
  {
    id: "web-10",
    title: "Accessibility & Technical SEO Builds",
    category: "web-dev",
    description: "WCAG-compliant semantic HTML structure with rich JSON-LD schemas.",
    deliverables: ["Accessibility Testing", "Schema Markup", "Semantic HTML5"],
    priceUSD: "$999 – $2,499",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "web-11",
    title: "Multi-Language Website Development",
    category: "web-dev",
    description: "Internationalization (i18n) for global & regional Indian markets.",
    deliverables: ["i18n Architecture", "Language Switcher", "Localized SEO Routes"],
    priceUSD: "$2,499 – $5,500",
    priceINR: "₹49,999 – ₹1,19,999",
  },
  {
    id: "web-12",
    title: "Web3 & Blockchain Frontend Integration",
    category: "web-dev",
    description: "Wallet connection, smart contract interactions & Web3 UI components.",
    deliverables: ["Wagmi/Ethers Integration", "WalletConnect", "Contract Calls"],
    priceUSD: "$3,500 – $8,500",
    priceINR: "₹79,999 – ₹1,89,999",
  },
  {
    id: "web-13",
    title: "Browser Extension Development",
    category: "web-dev",
    description: "Custom Chrome & Firefox extensions for productivity & automation.",
    deliverables: ["Manifest V3 Extension", "Background Scripts", "Popup UI"],
    priceUSD: "$2,999 – $6,500",
    priceINR: "₹59,999 – ₹1,39,999",
  },
  {
    id: "web-14",
    title: "Progressive Web App (PWA) Development",
    category: "web-dev",
    description: "Installable web apps with offline capabilities & push notifications.",
    deliverables: ["Service Workers", "Offline Mode", "Push Notifications"],
    priceUSD: "$3,500 – $7,500",
    priceINR: "₹69,999 – ₹1,59,999",
  },
  {
    id: "web-15",
    title: "Headless CMS Setup (Sanity / Contentful / Notion)",
    category: "web-dev",
    description: "Decoupled content architecture for easy editing by non-technical teams.",
    deliverables: ["CMS Schema Setup", "Webhooks", "Live Preview"],
    priceUSD: "$2,499 – $5,500",
    priceINR: "₹49,999 – ₹1,19,999",
  },
  {
    id: "web-16",
    title: "Custom Admin Dashboards & Admin Panels",
    category: "web-dev",
    description: "Data-dense analytics & management portals for internal operations.",
    deliverables: ["Role-Based Auth", "Interactive Charts", "Data Export"],
    priceUSD: "$3,999 – $9,500",
    priceINR: "₹79,999 – ₹1,99,999",
  },
  {
    id: "web-17",
    title: "SaaS Onboarding Flow Design",
    category: "web-dev",
    description: "Frictionless sign-up & checklist steps engineered to boost user activation.",
    deliverables: ["Step-by-Step Wizards", "Progress Tracking", "Activation Analytics"],
    priceUSD: "$1,999 – $4,500",
    priceINR: "₹39,999 – ₹99,999",
  },
  {
    id: "web-18",
    title: "Design System & Component Library Creation",
    category: "web-dev",
    description: "Reusable UI kit in Tailwind/Storybook for brand consistency across products.",
    deliverables: ["Tokens & Color Schemes", "React Components", "Documentation"],
    priceUSD: "$2,999 – $7,500",
    priceINR: "₹59,999 – ₹1,49,999",
  },
  {
    id: "web-19",
    title: "Pixel-Perfect Figma to Code Conversion",
    category: "web-dev",
    description: "Translating complex Figma designs into responsive Next.js/Tailwind code.",
    deliverables: ["Clean JSX Components", "Responsive Breakpoints", "Micro-Animations"],
    priceUSD: "$1,499 – $3,500",
    priceINR: "₹29,999 – ₹69,999",
  },
  {
    id: "web-20",
    title: "Strategic UI/UX Audit & Redesign",
    category: "web-dev",
    description: "In-depth UX teardown to remove conversion bottlenecks & UI clutter.",
    deliverables: ["UX Audit Deck", "Figma Wireframes", "Conversion Roadmap"],
    priceUSD: "$1,299 – $2,999",
    priceINR: "₹24,999 – ₹59,999",
  },

  /* ── 02: Process Automation & Systems Integration ── */
  {
    id: "auto-01",
    title: "Custom Conversational Chatbot Integration",
    category: "process-automation",
    description: "Interactive website chatbots built to qualify leads and answer FAQs 24/7.",
    deliverables: ["Embeddable Chat Widget", "Knowledge Integration", "Lead Escalation"],
    priceUSD: "$1,800 – $4,500",
    priceINR: "₹29,999 – ₹79,999",
  },
  {
    id: "auto-02",
    title: "WhatsApp Business Automation Setup",
    category: "process-automation",
    description: "Automated messaging infrastructure for customer inquiries & order updates.",
    deliverables: ["Official API Setup", "Message Templates", "Auto-Replies"],
    priceUSD: "$1,499 – $3,500",
    priceINR: "₹24,999 – ₹69,999",
    badge: "High Demand",
    isPopular: true,
  },
  {
    id: "auto-03",
    title: "Telegram & Discord Bot Architecture",
    category: "process-automation",
    description: "Automated community management, payment verification & user support bots.",
    deliverables: ["Custom Bot Logic", "Role Assignment", "Webhook Hooks"],
    priceUSD: "$1,299 – $2,999",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "auto-04",
    title: "Automated Customer Support Workflows",
    category: "process-automation",
    description: "Routing support queries, auto-resolving common tickets & CRM logging.",
    deliverables: ["Ticket Routing Rules", "Auto-Responses", "CRM Loggers"],
    priceUSD: "$2,499 – $5,500",
    priceINR: "₹49,999 – ₹1,19,999",
  },
  {
    id: "auto-05",
    title: "Appointment Booking & Scheduling Systems",
    category: "process-automation",
    description: "Calendar sync, SMS/WhatsApp reminders & automated rescheduling links.",
    deliverables: ["Google/Outlook Sync", "WhatsApp Reminders", "Cancellation Handling"],
    priceUSD: "$1,299 – $2,999",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "auto-06",
    title: "Automated WhatsApp Lead Follow-Up Sequences",
    category: "process-automation",
    description: "Timed drip messages to re-engage cold leads and drive conversions.",
    deliverables: ["3-Step Drip Sequence", "Opt-in Funnel", "Response Trackers"],
    priceUSD: "$999 – $2,499",
    priceINR: "₹14,999 – ₹39,999",
  },
  {
    id: "auto-07",
    title: "Lead Qualification Pipeline Architecture",
    category: "process-automation",
    description: "Scoring inbound leads by budget & urgency, routing hot leads to sales instantly.",
    deliverables: ["Lead Scoring Model", "Instant Notification", "CRM Tagging"],
    priceUSD: "$1,799 – $3,999",
    priceINR: "₹29,999 – ₹69,999",
  },
  {
    id: "auto-08",
    title: "Workflow Automation (n8n / Make / Zapier)",
    category: "process-automation",
    description: "Connecting apps, eliminating manual data entry & automating internal tasks.",
    deliverables: ["n8n / Make Blueprints", "Error Recovery", "API Connectors"],
    priceUSD: "$1,999 – $4,999",
    priceINR: "₹39,999 – ₹89,999",
  },
  {
    id: "auto-09",
    title: "CRM Integration & Database Sync",
    category: "process-automation",
    description: "Bi-directional sync between sales forms, messaging apps & CRM tools.",
    deliverables: ["HubSpot/Zoho Sync", "Data Normalization", "Real-Time Triggers"],
    priceUSD: "$1,799 – $3,999",
    priceINR: "₹29,999 – ₹69,999",
  },
  {
    id: "auto-10",
    title: "Smart Email Triage & Auto-Drafting",
    category: "process-automation",
    description: "Categorizing incoming emails and auto-preparing responses for staff review.",
    deliverables: ["Inbox Rules Engine", "Drafting Logic", "Urgency Alerts"],
    priceUSD: "$1,299 – $2,999",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "auto-11",
    title: "Document Processing Automation (Invoices & Contracts)",
    category: "process-automation",
    description: "Extracting structured data from incoming PDFs and inserting into ERP/CRM.",
    deliverables: ["PDF OCR Parsing", "Field Extraction", "ERP Integration"],
    priceUSD: "$2,499 – $5,999",
    priceINR: "₹49,999 – ₹1,19,999",
  },
  {
    id: "auto-12",
    title: "Internal Team Knowledge Base System",
    category: "process-automation",
    description: "Searchable internal knowledge search system built on your company documents.",
    deliverables: ["Doc Indexing", "Search Interface", "Access Control"],
    priceUSD: "$2,499 – $5,999",
    priceINR: "₹49,999 – ₹1,19,999",
  },
  {
    id: "auto-13",
    title: "Automated Business Performance Reports",
    category: "process-automation",
    description: "Weekly & monthly email executive summaries compiled automatically.",
    deliverables: ["Data Aggregation", "PDF/Email Reports", "KPI Tracking"],
    priceUSD: "$1,499 – $3,500",
    priceINR: "₹24,999 – ₹59,999",
  },
  {
    id: "auto-14",
    title: "Data Extraction Engine (PDFs, Images, Web)",
    category: "process-automation",
    description: "Automated scrapers & document parsers delivering structured CSV/JSON.",
    deliverables: ["Scraper Scripts", "CSV Exporter", "Scheduled Runs"],
    priceUSD: "$1,799 – $3,999",
    priceINR: "₹29,999 – ₹69,999",
  },
  {
    id: "auto-15",
    title: "Custom LLM Product Integration",
    category: "process-automation",
    description: "Embedding large language model capabilities into custom software apps.",
    deliverables: ["API Integration", "Prompt Engineering", "Cost Optimization"],
    priceUSD: "$4,999 – $12,500",
    priceINR: "₹99,999 – ₹2,49,999",
  },
  {
    id: "auto-16",
    title: "RAG & Vector Document Retrieval System",
    category: "process-automation",
    description: "Query your internal PDF files, databases & manuals with semantic search.",
    deliverables: ["Vector Database", "Embeddings Pipeline", "Chat Interface"],
    priceUSD: "$3,999 – $9,500",
    priceINR: "₹79,999 – ₹1,89,999",
  },
  {
    id: "auto-17",
    title: "Multi-Step Workflow Execution Engine",
    category: "process-automation",
    description: "Custom orchestration engines for multi-stage business operations.",
    deliverables: ["Orchestration Setup", "State Storage", "Audit Logging"],
    priceUSD: "$2,999 – $6,999",
    priceINR: "₹59,999 – ₹1,39,999",
  },
  {
    id: "auto-18",
    title: "Automated Social Media Publishing Pipelines",
    category: "process-automation",
    description: "Auto-scheduling posts across LinkedIn, Twitter & Instagram.",
    deliverables: ["Content Queue", "API Auto-Posters", "Analytics Sync"],
    priceUSD: "$1,299 – $2,999",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "auto-19",
    title: "Automated Review Monitoring & Response System",
    category: "process-automation",
    description: "Tracking Google reviews and preparing instant replies for manager approval.",
    deliverables: ["Review Aggregator", "Response Templates", "Sentiment Alerts"],
    priceUSD: "$999 – $2,499",
    priceINR: "₹14,999 – ₹39,999",
  },
  {
    id: "auto-20",
    title: "Automated Invoice & Billing Workflows",
    category: "process-automation",
    description: "Generating invoices upon job completion and issuing recurring receipts.",
    deliverables: ["Stripe/Razorpay Hooks", "PDF Invoices", "Overdue Triggers"],
    priceUSD: "$1,499 – $3,500",
    priceINR: "₹24,999 – ₹59,999",
  },
  {
    id: "auto-21",
    title: "Competitor Price & Alert Monitoring System",
    category: "process-automation",
    description: "Daily automated checks on competitor catalog pricing with email pings.",
    deliverables: ["Price Scraper", "Delta Alerts", "Daily Digest"],
    priceUSD: "$1,299 – $2,999",
    priceINR: "₹19,999 – ₹49,999",
  },

  /* ── 03: Audio & Voice Production ── */
  {
    id: "voice-01",
    title: "Professional Voiceover Production (Ads & Explainers)",
    category: "voice-audio",
    description: "High-grade vocal recordings for commercials, explainers & marketing videos.",
    deliverables: ["Mastered WAV Audio", "Commercial Rights", "Multiple Tones"],
    priceUSD: "$699 – $1,800",
    priceINR: "₹14,999 – ₹39,999",
  },
  {
    id: "voice-02",
    title: "Telephony Voice System & Voice Agent Setup",
    category: "voice-audio",
    description: "Automated inbound/outbound telephony call workflows for bookings & calls.",
    deliverables: ["SIP/Twilio Setup", "Call Scripts", "Live Call Transfer"],
    priceUSD: "$2,999 – $6,999",
    priceINR: "₹59,999 – ₹1,39,999",
  },
  {
    id: "voice-03",
    title: "Automated Reminder Voice Call Sequences",
    category: "voice-audio",
    description: "Outbound automated calls for appointment confirmations & payment reminders.",
    deliverables: ["Outbound Dialer", "Interactive Keypress", "Status Logging"],
    priceUSD: "$1,299 – $2,999",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "voice-04",
    title: "Voice IVR Script & Telephony Architecture",
    category: "voice-audio",
    description: "Designing corporate phone tree menus & routing calls efficiently.",
    deliverables: ["IVR Script Writing", "Audio Prompt Recordings", "Call Flow Routing"],
    priceUSD: "$1,499 – $3,500",
    priceINR: "₹24,999 – ₹59,999",
  },
  {
    id: "voice-05",
    title: "Multilingual Voice Dubbing & Localization",
    category: "voice-audio",
    description: "Dubbing content into regional Indian languages (Hindi, Odia, Telugu, Tamil).",
    deliverables: ["Subtitled Audio Sync", "Native Accents", "Language Master"],
    priceUSD: "$1,799 – $4,200",
    priceINR: "₹29,999 – ₹79,999",
  },
  {
    id: "voice-06",
    title: "Full Audiobook Production Pipeline",
    category: "voice-audio",
    description: "End-to-end audio production from text script to Audible-ready audio files.",
    deliverables: ["ACX Standard Audio", "Chapter Mastering", "Noise Reduction"],
    priceUSD: "$2,499 – $5,999",
    priceINR: "₹49,999 – ₹1,19,999",
  },
  {
    id: "voice-07",
    title: "Podcast Scripting Briefs & Intro/Outro Production",
    category: "voice-audio",
    description: "Crafting professional show intros, outro calls-to-action & jingle briefs.",
    deliverables: ["Broadcast Intros", "Show Notes Script", "Audio Editing"],
    priceUSD: "$899 – $1,999",
    priceINR: "₹14,999 – ₹39,999",
  },
  {
    id: "voice-08",
    title: "Podcast Show Notes & Timestamp Generator",
    category: "voice-audio",
    description: "Extracting bulleted summaries, quotes & chapter timestamps from raw audio.",
    deliverables: ["Timestamped Markdown", "Key Insights", "SEO Show Notes"],
    priceUSD: "$699 – $1,499",
    priceINR: "₹9,999 – ₹24,999",
  },
  {
    id: "voice-09",
    title: "Video Auto-Captioning & Subtitle Production",
    category: "voice-audio",
    description: "Generating styled subtitle files (.srt, .vtt) burned into short-form videos.",
    deliverables: ["SRT Files", "Dynamic Subtitles", "Font Customization"],
    priceUSD: "$499 – $1,199",
    priceINR: "₹7,999 – ₹19,999",
  },
  {
    id: "voice-10",
    title: "Voiceover Production for Video Channels",
    category: "voice-audio",
    description: "Consistent voice narration for brand channels & instructional videos.",
    deliverables: ["Weekly Narration", "Clean Audio Tracks", "Tone Matching"],
    priceUSD: "$1,199 – $2,799",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "voice-11",
    title: "Regional Language Telephony Voice Setup",
    category: "voice-audio",
    description: "Local Indian accent voice prompts for Tier 2/3 regional business callers.",
    deliverables: ["Odia/Hindi Voice", "Call Routing", "Local Dialect Matching"],
    priceUSD: "$1,799 – $3,999",
    priceINR: "₹29,999 – ₹69,999",
  },
  {
    id: "voice-12",
    title: "Professional Audio Demo Reel Production",
    category: "voice-audio",
    description: "Editing audio samples into sleek demo reels for speakers & creators.",
    deliverables: ["Mastered Demo Track", "Noise Cleaning", "Visualizer Video"],
    priceUSD: "$699 – $1,499",
    priceINR: "₹9,999 – ₹24,999",
  },

  /* ── 04: Content & Conversion Copywriting ── */
  {
    id: "copy-01",
    title: "High-Converting Website Copywriting",
    category: "content-copy",
    description: "Compelling messaging for homepages, about pages & core service offerings.",
    deliverables: ["Full Brand Copy", "Value Proposition", "CTAs & Micro-Copy"],
    priceUSD: "$1,499 – $3,500",
    priceINR: "₹24,999 – ₹69,999",
  },
  {
    id: "copy-02",
    title: "Landing Page Copy with Conversion Optimization",
    category: "content-copy",
    description: "Persuasive sales copywriting engineered to maximize paid campaign ROI.",
    deliverables: ["Headline Variations", "Objection Handling", "High-Converting CTAs"],
    priceUSD: "$999 – $2,499",
    priceINR: "₹19,999 – ₹49,999",
    badge: "Popular",
    isPopular: true,
  },
  {
    id: "copy-03",
    title: "SEO Article & Editorial Content Writing",
    category: "content-copy",
    description: "In-depth blog content optimized for target keywords & search intent.",
    deliverables: ["Search-Intent Match", "Internal Linking", "Meta Tags included"],
    priceUSD: "$699 – $1,800",
    priceINR: "₹9,999 – ₹29,999",
  },
  {
    id: "copy-04",
    title: "Strategic Email Newsletter Campaigns",
    category: "content-copy",
    description: "Engaging weekly or monthly email content that keeps subscribers hooked.",
    deliverables: ["Subject Line Testing", "Value-Packed Body Copy", "Newsletter Design"],
    priceUSD: "$799 – $1,800",
    priceINR: "₹12,999 – ₹34,999",
  },
  {
    id: "copy-05",
    title: "YouTube Video Scripts & Storyboards",
    category: "content-copy",
    description: "Structured video scripts with retention hooks, body breakdowns & CTAs.",
    deliverables: ["Hook Optimization", "Visual Cues", "Pacing Guidance"],
    priceUSD: "$599 – $1,499",
    priceINR: "₹9,999 – ₹24,999",
  },
  {
    id: "copy-06",
    title: "Short-Form Video Script Batching (Reels & Shorts)",
    category: "content-copy",
    description: "30-second video script batches built for Instagram Reels & YouTube Shorts.",
    deliverables: ["Batch of 10 Scripts", "Pattern Interrupt Hooks", "On-screen Text"],
    priceUSD: "$799 – $1,800",
    priceINR: "₹12,999 – ₹34,999",
  },
  {
    id: "copy-07",
    title: "Executive LinkedIn Ghostwriting & Positioning",
    category: "content-copy",
    description: "Thought leadership content for founders & executives to build authority.",
    deliverables: ["Weekly Posts Batch", "Profile Optimization", "Engagement Angles"],
    priceUSD: "$1,199 – $2,800",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "copy-08",
    title: "Content Repurposing Pipeline (Blog to Social)",
    category: "content-copy",
    description: "Turning single long-form articles or videos into multi-platform social posts.",
    deliverables: ["1 Article → 5 Tweets", "LinkedIn Carousel", "Newsletter Snippet"],
    priceUSD: "$999 – $2,200",
    priceINR: "₹14,999 – ₹39,999",
  },
  {
    id: "copy-09",
    title: "E-Commerce Bulk Product Description Writing",
    category: "content-copy",
    description: "Writing benefits-driven, search-optimized product copy in bulk.",
    deliverables: ["CSV Export", "Feature-to-Benefit Copy", "SEO Keyword Tags"],
    priceUSD: "$1,199 – $2,800",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "copy-10",
    title: "Official Press Release Writing",
    category: "content-copy",
    description: "Journalist-formatted press releases for product launches & announcements.",
    deliverables: ["Standard PR Format", "Executive Quotes", "Media Kit Copy"],
    priceUSD: "$799 – $1,800",
    priceINR: "₹12,999 – ₹29,999",
  },
  {
    id: "copy-11",
    title: "Case Study Writing from Client Interviews",
    category: "content-copy",
    description: "Converting customer interview transcripts into high-trust case studies.",
    deliverables: ["Problem/Solution/Results", "Verified Metrics", "PDF + Web Layout"],
    priceUSD: "$999 – $2,499",
    priceINR: "₹14,999 – ₹39,999",
  },
  {
    id: "copy-12",
    title: "Knowledge Base & Help Center Writing",
    category: "content-copy",
    description: "Clear support articles, step-by-step guides & troubleshooting documentation.",
    deliverables: ["Categorized Articles", "Screenshots Guidance", "Search Tags"],
    priceUSD: "$1,199 – $2,800",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "copy-13",
    title: "Technical API Documentation Writing",
    category: "content-copy",
    description: "Developer-friendly API reference docs, code snippets & endpoint guides.",
    deliverables: ["Swagger/OpenAPI Copy", "Code Samples", "Quickstart Guides"],
    priceUSD: "$1,799 – $4,200",
    priceINR: "₹29,999 – ₹79,999",
  },
  {
    id: "copy-14",
    title: "App Store & Play Store Listing Copy",
    category: "content-copy",
    description: "ASO-optimized app titles, short descriptions & screenshot copy.",
    deliverables: ["Keyword Strategy", "Short & Long Description", "Release Notes"],
    priceUSD: "$799 – $1,800",
    priceINR: "₹12,999 – ₹29,999",
  },
  {
    id: "copy-15",
    title: "Pitch Deck Content & Narrative Copywriting",
    category: "content-copy",
    description: "Investor pitch narrative, market problem framing & slide copy.",
    deliverables: ["10-12 Slide Copy", "Financial Narrative", "Elevator Pitch"],
    priceUSD: "$1,999 – $4,999",
    priceINR: "₹34,999 – ₹89,999",
  },
  {
    id: "copy-16",
    title: "Investor Update Email Templates",
    category: "content-copy",
    description: "Structured templates for monthly/quarterly shareholder progress reports.",
    deliverables: ["Metrics Table Copy", "Highlights & Lowlights", "Ask Section"],
    priceUSD: "$799 – $1,500",
    priceINR: "₹12,999 – ₹24,999",
  },
  {
    id: "copy-17",
    title: "Startup One-Pager & Memorandum Copy",
    category: "content-copy",
    description: "Single-page executive teardowns summarizing business models & metrics.",
    deliverables: ["Executive One-Pager", "Value Proposition", "Key Traction Points"],
    priceUSD: "$999 – $2,200",
    priceINR: "₹14,999 – ₹34,999",
  },
  {
    id: "copy-18",
    title: "Automated Git Commit Changelog Generator",
    category: "content-copy",
    description: "Pipelines that parse git commits into clean public release notes.",
    deliverables: ["Git Hook Setup", "Markdown Exporter", "Clean Categorization"],
    priceUSD: "$599 – $1,299",
    priceINR: "₹9,999 – ₹19,999",
  },
  {
    id: "copy-19",
    title: "Release Notes Writing for Non-Technical Users",
    category: "content-copy",
    description: "Translating code pull requests into engaging feature update announcements.",
    deliverables: ["Plain English Copy", "Feature Highlight GIF Guidance", "Email Digest"],
    priceUSD: "$699 – $1,499",
    priceINR: "₹9,999 – ₹24,999",
  },
  {
    id: "copy-20",
    title: "Client Progress Report Generation Pipeline",
    category: "content-copy",
    description: "Automated monthly report summaries written for retainer clients.",
    deliverables: ["Executive Summary Copy", "KPI Breakdown", "Action Plan"],
    priceUSD: "$799 – $1,800",
    priceINR: "₹12,999 – ₹29,999",
  },

  /* ── 05: Marketing & Growth Engineering ── */
  {
    id: "mktg-01",
    title: "Technical & On-Page SEO Implementation",
    category: "marketing-growth",
    description: "Complete technical audit, canonical structure, sitemap & page indexing.",
    deliverables: ["Technical Fixes", "On-Page Metadata", "Internal Link Mesh"],
    priceUSD: "$1,499 – $3,500",
    priceINR: "₹24,999 – ₹69,999",
  },
  {
    id: "mktg-02",
    title: "Google Business Profile & Local SEO",
    category: "marketing-growth",
    description: "Local search optimization to rank in the Google Maps top-3 snack pack.",
    deliverables: ["Profile Audit", "Review Acquisition Engine", "Local Citations"],
    priceUSD: "$999 – $2,200",
    priceINR: "₹14,999 – ₹39,999",
    badge: "Popular",
    isPopular: true,
  },
  {
    id: "mktg-03",
    title: "Google Ads Campaign Setup & Management",
    category: "marketing-growth",
    description: "Intent-based Search & Performance Max campaigns tuned for conversion.",
    deliverables: ["Keyword Strategy", "Ad Group Architecture", "Negative Keywords"],
    priceUSD: "$1,799 – $4,500",
    priceINR: "₹29,999 – ₹79,999",
  },
  {
    id: "mktg-04",
    title: "Meta Ads (Facebook & Instagram) Setup",
    category: "marketing-growth",
    description: "Direct-response ad campaigns with custom audience targeting & pixel tracking.",
    deliverables: ["Pixel & CAPI Setup", "Audience Clusters", "Ad Creative Briefs"],
    priceUSD: "$1,799 – $4,500",
    priceINR: "₹29,999 – ₹79,999",
  },
  {
    id: "mktg-05",
    title: "Multi-Variation Ad Copy & Creative Testing",
    category: "marketing-growth",
    description: "Generating 5-10 hook & angle variations to find top performing ad assets.",
    deliverables: ["Angle Variations", "Headline A/B Sets", "Winner Flagging"],
    priceUSD: "$999 – $2,200",
    priceINR: "₹14,999 – ₹39,999",
  },
  {
    id: "mktg-06",
    title: "Email Marketing Automation & Drip Sequences",
    category: "marketing-growth",
    description: "Welcome, onboarding, abandoned cart & customer nurture automation flows.",
    deliverables: ["Klaviyo / Brevo Setup", "5-Step Email Sequence", "Custom Design"],
    priceUSD: "$1,299 – $3,200",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "mktg-07",
    title: "Cold Email Outreach Campaigns & Personalization",
    category: "marketing-growth",
    description: "Infrastructure setup (domain warmup, SPF/DKIM) & targeted cold outreach.",
    deliverables: ["Domain Infrastructure", "Personalized Templates", "Reply Handling"],
    priceUSD: "$1,800 – $4,500",
    priceINR: "₹29,999 – ₹79,999",
  },
  {
    id: "mktg-08",
    title: "WhatsApp Marketing & Broadcast Sequences",
    category: "marketing-growth",
    description: "Opt-in funnels, promotional broadcasts & automated customer re-engagement.",
    deliverables: ["Broadcast Setup", "Opt-in Widget", "Compliance Checks"],
    priceUSD: "$1,199 – $2,800",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "mktg-09",
    title: "Lead Generation Funnel Architecture",
    category: "marketing-growth",
    description: "High-converting lead magnets, squeeze pages & instant email delivery.",
    deliverables: ["Lead Magnet Asset", "Squeeze Page", "Delivery Automation"],
    priceUSD: "$1,999 – $4,999",
    priceINR: "₹34,999 – ₹89,999",
  },
  {
    id: "mktg-10",
    title: "LinkedIn B2B Growth & Outreach Funnels",
    category: "marketing-growth",
    description: "Targeted outbound prospecting & relationship building for high-ticket B2B.",
    deliverables: ["ICP Target List", "Message Templates", "Connection Sequence"],
    priceUSD: "$1,799 – $4,200",
    priceINR: "₹29,999 – ₹69,999",
  },
  {
    id: "mktg-11",
    title: "GA4 Analytics & Looker Studio Dashboards",
    category: "marketing-growth",
    description: "Custom attribution reporting dashboards tracking ROI across channels.",
    deliverables: ["GA4 Conversion Events", "Looker Studio Dashboard", "Monthly Digest"],
    priceUSD: "$1,199 – $2,800",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "mktg-12",
    title: "Conversion Rate Optimization (CRO) Audits",
    category: "marketing-growth",
    description: "Heatmap setup (Clarity/Hotjar) & user drop-off analysis to lift sales.",
    deliverables: ["Heatmap Setup", "Drop-Off Report", "UX Action Plan"],
    priceUSD: "$999 – $2,499",
    priceINR: "₹14,999 – ₹39,999",
  },
  {
    id: "mktg-13",
    title: "Brand Messaging & Value Proposition Strategy",
    category: "marketing-growth",
    description: "Defining brand voice, positioning statement & competitor teardown guide.",
    deliverables: ["Brand Tone Book", "Taglines", "Competitor Matrix"],
    priceUSD: "$1,499 – $3,500",
    priceINR: "₹24,999 – ₹59,999",
  },

  /* ── 07: Data & Market Intelligence ── */
  {
    id: "data-01",
    title: "Strategic Market Research Reports",
    category: "data-research",
    description: "Niche industry breakdowns, TAM analysis & market opportunity reports.",
    deliverables: ["Executive PDF Deck", "Data Sources", "Opportunity Matrix"],
    priceUSD: "$1,799 – $4,200",
    priceINR: "₹29,999 – ₹69,999",
  },
  {
    id: "data-02",
    title: "Competitor Teardown & Positioning Reports",
    category: "data-research",
    description: "In-depth teardowns of competitor landing pages, pricing models & messaging.",
    deliverables: ["Feature Matrix", "Pricing Benchmark", "Messaging Gaps"],
    priceUSD: "$1,199 – $2,800",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "data-03",
    title: "Customer Survey & Sentiment Insight Reports",
    category: "data-research",
    description: "Synthesizing raw user survey feedback into clear product development priorities.",
    deliverables: ["Survey Processing", "Sentiment Clusters", "Actionable Plan"],
    priceUSD: "$999 – $2,200",
    priceINR: "₹14,999 – ₹39,999",
  },
  {
    id: "data-04",
    title: "Automated Web Scraping & Data Extraction",
    category: "data-research",
    description: "Custom web crawlers delivering clean lead lists, directories or catalog data.",
    deliverables: ["Clean CSV/JSON File", "Crawler Script", "Data Verification"],
    priceUSD: "$1,499 – $3,500",
    priceINR: "₹24,999 – ₹59,999",
  },
  {
    id: "data-05",
    title: "SaaS Pricing Benchmarking Reports",
    category: "data-research",
    description: "Analysis of category pricing tiers, packaging strategies & expansion loops.",
    deliverables: ["Category Pricing Deck", "Tier Recommendations", "Add-on Strategy"],
    priceUSD: "$999 – $2,499",
    priceINR: "₹14,999 – ₹39,999",
  },
  {
    id: "data-06",
    title: "Audience Segmentation & Persona Profiling",
    category: "data-research",
    description: "Detailed ICP buyer persona cards outlining pain points, objections & triggers.",
    deliverables: ["3 Buyer Persona Cards", "Objection Handling Guide", "Channel Map"],
    priceUSD: "$1,199 – $2,500",
    priceINR: "₹19,999 – ₹44,999",
  },

  /* ── 08: India & Regional Market Solutions ── */
  {
    id: "ind-01",
    title: "Regional Vernacular Ad Copywriting",
    category: "india-localization",
    description: "High-converting ad copy localized into Hindi, Odia, Telugu, Tamil & Bengali.",
    deliverables: ["6 Language Variants", "Cultural Context Match", "Ad Angles"],
    priceUSD: "$799 – $1,800",
    priceINR: "₹12,999 – ₹29,999",
    badge: "Regional Focus",
  },
  {
    id: "ind-02",
    title: "Razorpay Payment Gateway & Checkout Flow",
    category: "india-localization",
    description: "UPI auto-pay, netbanking & Razorpay checkout integration for Indian customers.",
    deliverables: ["UPI Integration", "Subscription Auto-Pay", "Webhook Verification"],
    priceUSD: "$999 – $2,200",
    priceINR: "₹14,999 – ₹39,999",
  },
  {
    id: "ind-03",
    title: "WhatsApp Business Catalog Architecture",
    category: "india-localization",
    description: "Setting up product catalogs directly inside WhatsApp for Tier 2/3 sales.",
    deliverables: ["WhatsApp Catalog Setup", "Product Copy", "Direct Order Hooks"],
    priceUSD: "$799 – $1,800",
    priceINR: "₹12,999 – ₹29,999",
  },
  {
    id: "ind-04",
    title: "Bharat-First Landing Page Localization",
    category: "india-localization",
    description: "Adapting landing pages for low-bandwidth mobile users & Indian UX expectations.",
    deliverables: ["Sub-100KB Page Weight", "WhatsApp CTA First", "Language Switcher"],
    priceUSD: "$1,299 – $2,999",
    priceINR: "₹19,999 – ₹49,999",
  },
  {
    id: "ind-05",
    title: "Regional Telephony Voice Setup",
    category: "india-localization",
    description: "Configuring phone IVRs with native Odia/Hindi voice prompts for regional callers.",
    deliverables: ["Native Dialects", "Interactive Menu", "SMS Link Send"],
    priceUSD: "$1,799 – $3,999",
    priceINR: "₹29,999 – ₹69,999",
  },
  {
    id: "ind-06",
    title: "CA / CS / CMA Exam Prep Content Modules",
    category: "india-localization",
    description: "Structured question banks & study modules for Indian professional exams.",
    deliverables: ["Structured PYQs", "Format Alignment", "Exportable Tests"],
    priceUSD: "$1,199 – $2,800",
    priceINR: "₹19,999 – ₹49,999",
  },
];

/* ─── Category 09: Autonomous AI Agents (Monthly Retainer) ─────────────────── */

export type AutonomousAgentCategory = {
  categoryName: string;
  agents: {
    name: string;
    description: string;
    actionDetail: string;
    priceUSD: string;
    priceINR: string;
  }[];
};

export const AI_AGENT_CATEGORIES: AutonomousAgentCategory[] = [
  {
    categoryName: "Sales & Business Development AI Agents",
    agents: [
      {
        name: "Lead Generation Agent",
        description: "Autonomous Web Scraper & Qualification Engine",
        actionDetail: "Scrapes the web daily matching your ICP, verifies emails & builds qualified lead lists automatically.",
        priceUSD: "$999/mo",
        priceINR: "₹24,999/mo",
      },
      {
        name: "Cold Outreach Agent",
        description: "Autonomous Multichannel Email & LinkedIn Sender",
        actionDetail: "Sends hyper-personalized cold outreach messages at scale & handles initial response triage.",
        priceUSD: "$1,199/mo",
        priceINR: "₹29,999/mo",
      },
      {
        name: "Meeting Booking Agent",
        description: "Autonomous Lead Qualifier & Calendar Booker",
        actionDetail: "Chats with inbound visitors on WhatsApp/Web, qualifies budget & books meetings directly into your calendar.",
        priceUSD: "$799/mo",
        priceINR: "₹19,999/mo",
      },
      {
        name: "CRM Update Agent",
        description: "Autonomous Call & Email Data Logger",
        actionDetail: "Listens to sales recordings & email threads, auto-populating custom deal fields in HubSpot or Zoho.",
        priceUSD: "$599/mo",
        priceINR: "₹14,999/mo",
      },
    ],
  },
  {
    categoryName: "Customer Support AI Agents",
    agents: [
      {
        name: "24/7 Multilingual Support Agent",
        description: "Autonomous WhatsApp & Website Support Engine",
        actionDetail: "Resolves customer FAQs, order tracking & inquiries in English, Hindi, Odia & regional languages 24/7.",
        priceUSD: "$899/mo",
        priceINR: "₹24,999/mo",
      },
      {
        name: "Ticket Triage & Routing Agent",
        description: "Autonomous Helpdesk Classifier",
        actionDetail: "Reads incoming support tickets, categorizes urgency & routes complex issues to human agents instantly.",
        priceUSD: "$599/mo",
        priceINR: "₹14,999/mo",
      },
      {
        name: "Review & Reputation Response Agent",
        description: "Autonomous Review Collector & Responder",
        actionDetail: "Monitors Google Maps & app reviews, auto-drafting brand-toned replies & requesting post-service reviews.",
        priceUSD: "$499/mo",
        priceINR: "₹12,999/mo",
      },
    ],
  },
  {
    categoryName: "Marketing & Operations AI Agents",
    agents: [
      {
        name: "SEO Content Writing Agent",
        description: "Autonomous Keyword Researcher & Publisher",
        actionDetail: "Researches low-competition keywords, drafts complete SEO posts & schedules them directly in your CMS.",
        priceUSD: "$799/mo",
        priceINR: "₹19,999/mo",
      },
      {
        name: "Content Repurposing Agent",
        description: "Autonomous Video & Article Transfomer",
        actionDetail: "Parses long video links into Twitter threads, LinkedIn carousels & Shorts scripts automatically.",
        priceUSD: "$599/mo",
        priceINR: "₹14,999/mo",
      },
      {
        name: "Invoice & Overdue Payment Agent",
        description: "Autonomous Accounts Receivable Follow-up",
        actionDetail: "Monitors unpaid invoices and sends timed, polite escalation messages until payment is logged.",
        priceUSD: "$699/mo",
        priceINR: "₹17,999/mo",
      },
    ],
  },
];
