-- ==========================================
-- SQL Schema Setup for youtube_subscribers
-- Run this in the Supabase SQL Editor of your ExamOS project
-- ==========================================

-- 1. Create the table
CREATE TABLE IF NOT EXISTS public.youtube_subscribers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
-- This is critical so that database access is locked down by default.
ALTER TABLE public.youtube_subscribers ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policy for Inserting Subscribers
-- This policy allows anonymous (public) visitors of your landing page to submit their emails.
-- It maps to the 'anon' role which is used when calling via the NEXT_PUBLIC_SUPABASE_ANON_KEY.
CREATE POLICY "Allow public inserts to youtube_subscribers" 
ON public.youtube_subscribers 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- 4. Create RLS Policy for Selecting/Viewing Subscribers (Optional but recommended)
-- This policy allows authenticated users (like you as an admin/owner) to view the subscribers list.
CREATE POLICY "Allow authenticated users to view youtube_subscribers" 
ON public.youtube_subscribers 
FOR SELECT 
TO authenticated 
USING (true);
