"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import {
  MessageCircle,
  Zap,
  Globe,
  Check,
  X,
  PhoneCall,
  HelpCircle,
  Sparkles,
  ArrowRight,
  ShieldCheck,
  Code2,
  Clock,
  CheckCircle2,
  TrendingUp,
  Bot,
  Layers,
} from "lucide-react";
import {
  PRICING_AGENTS,
  PRICING_WEBSITES,
  PRICING_MARKETING,
  PRICING_CONTENT,
  PRICING_ADDONS,
  PRICING_FAQ,
  waLink,
} from "@/lib/site";
import { DotGridBackdrop } from "@/components/ui/dot-grid-backdrop";
import { cn } from "@/lib/utils";

type FeatureDetail = {
  outcome: string;
  description: string;
  benefits: string[];
};

const FEATURE_DETAILS: Record<string, FeatureDetail> = {
  "WhatsApp AI Receptionist": {
    outcome: "Never miss a lead—even after business hours.",
    description:
      "A 24/7 conversational agent integrated directly into your WhatsApp Business number. Trained on your treatments, pricing, and services to answer FAQs, qualify leads, and direct users to booking options.",
    benefits: [
      "Instantly handles unlimited concurrent chats",
      "Answers common questions without human staff",
      "Qualifies leads so you only talk to serious clients",
    ],
  },
  "Appointment Booking": {
    outcome: "Fill your calendar automatically.",
    description:
      "Allows leads to schedule consultations or service slots directly within chat. Syncs dynamically with your Google Calendar, Outlook, or booking platforms in real-time.",
    benefits: [
      "Eliminates back-and-forth calendar coordination",
      "Blocks double-bookings instantly",
      "Auto-sends calendar invites to both parties",
    ],
  },
  "Smart Reminders": {
    outcome: "Reduce appointment no-shows by up to 50%.",
    description:
      "Automatically sends personalized, friendly reminders to clients before their scheduled appointments. Allows them to confirm, reschedule, or cancel directly from their text threads.",
    benefits: [
      "Drastically reduces empty slots and missed bookings",
      "Sends timely reminders via WhatsApp, SMS, or Email",
      "Updates calendar status automatically",
    ],
  },
  "Follow-up Agent": {
    outcome: "Recover leads that normally never reply.",
    description:
      "An automated sequence builder that keeps in touch with leads on a regular schedule. Re-engages cold leads, checks in after consultations, and collects post-visit satisfaction data.",
    benefits: [
      "Nurtures leads without manual follow-up effort",
      "Re-activates old prospects with custom offers",
      "Identifies customer satisfaction issues early",
    ],
  },
  "Review Manager": {
    outcome: "Build instant trust with automated 5-star reviews.",
    description:
      "Systematically requests Google reviews and business feedback 2 hours after a successful purchase or appointment. Integrates review aggregation and auto-suggests replies in your brand tone.",
    benefits: [
      "Increases Google reviews by 2x to 3x within 60 days",
      "Helps you rank higher on local Google Search results",
      "Boosts local buyer confidence automatically",
    ],
  },
  "Lead Qualifier": {
    outcome: "Filter out tire-kickers. Route hot leads only.",
    description:
      "Intelligent inbound lead scoring. Automatically chats with prospective clients, scoring them based on budget, urgency, and requirement alignment before passing them to your sales team.",
    benefits: [
      "Saves up to 80% of sales reps' calling time",
      "Instantly tags leads as hot, warm, or cold",
      "Forwards high-priority leads with summaries to WhatsApp",
    ],
  },
  "Content Agent": {
    outcome: "Launch your content machine on autopilot.",
    description:
      "An AI content coordinator that drafts weekly blogs, newsletter articles, and social media posts tailored to your brand voice, industry trends, and local business keyword targets.",
    benefits: [
      "Consistent marketing presence without content block",
      "SEO-ready blog drafts mapped to local searches",
      "Quick approval flow: edit and schedule in seconds",
    ],
  },
  "Analytics Dashboard": {
    outcome: "See every missed opportunity in one dashboard.",
    description:
      "A centralized dashboard displaying active client conversations, lead capture rates, automated appointments booked, and estimated ROI generated by Next Scale automation systems.",
    benefits: [
      "Track exact revenue generated by the AI",
      "Identify conversational drop-off points",
      "Compare week-over-week performance in real-time",
    ],
  },
  Support: {
    outcome: "Continuous optimization from dedicated experts.",
    description:
      "Ongoing support packages providing regular prompt updates, fine-tuning audits, custom configuration expansions, and active monitoring to ensure your agents are performing at their peak.",
    benefits: [
      "Prompt tuning based on real-world conversations",
      "Priority assistance over WhatsApp or dedicated Slack channel",
      "Constant updates aligned with OpenAI/Meta API rollouts",
    ],
  },
};

const MARQUEE_ITEMS = [
  "⚡ Transparent Upfront Pricing",
  "🔒 100% Source Code Handover",
  "🚀 Shipped in 5 to 7 Days",
  "🤖 24/7 WhatsApp AI Agents",
  "💳 Zero Surprise Retainers",
  "💬 Direct Founder WhatsApp Support",
  "🌍 Serving Clients in 8+ Countries",
  "🎯 99/100 Google PageSpeed",
];

const GUARANTEES = [
  {
    icon: Code2,
    title: "100% Code Ownership",
    desc: "You own all GitHub repositories, domains, and assets. No proprietary host lock-in.",
  },
  {
    icon: Zap,
    title: "Sub-Second Load Times",
    desc: "Mobile-first Next.js architecture ensuring 95+ PageSpeed scores on every device.",
  },
  {
    icon: Clock,
    title: "7-Day Sprint Delivery",
    desc: "Rapid deployment cycles. We launch functional systems in days, not months.",
  },
  {
    icon: ShieldCheck,
    title: "Zero Hidden Fees",
    desc: "Fixed upfront scopes. You will never receive an unexpected maintenance invoice.",
  },
  {
    icon: Sparkles,
    title: "30-Day Launch Support",
    desc: "Post-launch prompt tuning, analytics tracking, and bug fixes included at zero cost.",
  },
  {
    icon: PhoneCall,
    title: "Direct WhatsApp Line",
    desc: "Direct communication with engineers. Zero account manager telephone games.",
  },
];

export default function PricingPage() {
  const [isINR, setIsINR] = useState<boolean>(false);
  const [isAnnual, setIsAnnual] = useState<boolean>(false);
  const [currencyReady, setCurrencyReady] = useState<boolean>(false);
  const [activeFeature, setActiveFeature] = useState<string | null>(null);

  useEffect(() => {
    const saved = localStorage.getItem("currencyPreference");
    if (saved) {
      setIsINR(saved === "INR");
    } else {
      setIsINR(false);
    }
    setCurrencyReady(true);
  }, []);

  const toggleCurrency = (curr: "INR" | "USD") => {
    setIsINR(curr === "INR");
    localStorage.setItem("currencyPreference", curr);
  };

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") setActiveFeature(null);
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  const JUMP_LINKS = [
    { id: "websites", label: "Websites" },
    { id: "agents", label: "AI Agents" },
    { id: "suite", label: "Growth Suite" },
    { id: "marketing", label: "Marketing" },
    { id: "content", label: "Content" },
    { id: "addons", label: "Add-ons" },
    { id: "faq", label: "FAQ" },
  ];

  return (
    <div className="overflow-hidden pt-[4.5rem] sm:pt-24">
      {/* Ticker Marquee */}
      <div className="border-b border-slate-200 bg-blue-50/80 py-2.5 overflow-hidden">
        <div className="animate-marquee flex items-center gap-8 whitespace-nowrap font-mono text-xs font-bold uppercase tracking-wider text-blue-900">
          {[...MARQUEE_ITEMS, ...MARQUEE_ITEMS].map((item, i) => (
            <span key={i} className="flex items-center gap-3">
              <span>{item}</span>
              <span className="size-1.5 rounded-full bg-blue-600" />
            </span>
          ))}
        </div>
      </div>

      {/* Hero Section */}
      <section className="relative border-b border-slate-200 bg-slate-50/50 px-5 py-16 sm:px-8 sm:py-24 overflow-hidden">
        {/* Interactive Physics DotGrid Backdrop from ReactBits */}
        <DotGridBackdrop />

        <div className="relative z-10 mx-auto max-w-[1280px]">
          <div className="flex flex-col items-center text-center">
            <div className="flex flex-wrap items-center justify-center gap-3 mb-6">
              <span className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3.5 py-1.5 font-mono text-xs font-semibold text-blue-700 shadow-xs">
                <Sparkles className="size-3.5" /> Launch Pricing
              </span>
              <span className="font-mono text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">
                Save up to 50%
              </span>
            </div>

            <h1 className="max-w-4xl font-heading text-4xl font-extrabold uppercase tracking-tight sm:text-6xl md:text-7xl text-slate-900">
              Clear numbers. <br />
              <span className="text-blue-600">Compounding ROI.</span>
            </h1>

            <p className="mt-6 max-w-2xl text-lg font-medium leading-relaxed text-slate-600 sm:text-xl">
              Transparent pricing for custom Next.js websites, 24/7 WhatsApp AI receptionists, and digital growth engines. No mystery invoices.
            </p>

            {/* Currency & Annual Switcher Widget */}
            <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4">
              {/* Currency Selector */}
              <div className="inline-flex items-center rounded-full border border-slate-200 bg-white p-1 shadow-xs">
                <button
                  type="button"
                  onClick={() => toggleCurrency("USD")}
                  className={`flex items-center gap-1.5 rounded-full px-4 min-h-[40px] font-mono text-xs font-bold uppercase transition-all ${
                    !isINR ? "bg-blue-600 text-white shadow-xs" : "text-slate-600 hover:text-slate-900"
                  }`}
                >
                  <Globe className="size-3.5" /> USD ($) Global
                </button>
                <button
                  type="button"
                  onClick={() => toggleCurrency("INR")}
                  className={`flex items-center gap-1.5 rounded-full px-4 min-h-[40px] font-mono text-xs font-bold uppercase transition-all ${
                    isINR ? "bg-blue-600 text-white shadow-xs" : "text-slate-600 hover:text-slate-900"
                  }`}
                >
                  🇮🇳 INR (₹) India
                </button>
              </div>

              {/* Annual Toggle */}
              <div className="inline-flex items-center gap-3 rounded-full border border-slate-200 bg-white px-4 py-2.5 shadow-xs">
                <span className={cn("font-mono text-xs font-bold uppercase", !isAnnual ? "text-slate-900" : "text-slate-400")}>
                  Monthly
                </span>
                <button
                  type="button"
                  onClick={() => setIsAnnual(!isAnnual)}
                  aria-label={isAnnual ? "Switch to monthly billing" : "Switch to annual billing"}
                  className="relative inline-flex h-7 w-14 items-center rounded-full bg-slate-200 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600"
                >
                  <span
                    className={cn(
                      "inline-block size-5 transform rounded-full bg-blue-600 transition-transform shadow-sm",
                      isAnnual ? "translate-x-7" : "translate-x-1"
                    )}
                  />
                </button>
                <span className={cn("flex items-center gap-1.5 font-mono text-xs font-bold uppercase", isAnnual ? "text-slate-900" : "text-slate-400")}>
                  Annual
                  <span className="rounded-full bg-emerald-50 border border-emerald-200 px-2 py-0.5 text-[0.6rem] font-bold text-emerald-800">
                    SAVE 17%
                  </span>
                </span>
              </div>
            </div>

            {/* Jump Anchor Bar */}
            <div className="mt-8 flex flex-wrap items-center justify-center gap-2">
              {JUMP_LINKS.map((j) => (
                <a
                  key={j.id}
                  href={`#${j.id}`}
                  className="rounded-full border border-slate-200 bg-white px-3.5 py-1.5 min-h-[32px] inline-flex items-center font-mono text-[0.65rem] font-semibold uppercase tracking-[0.06em] text-slate-700 shadow-xs transition hover:border-blue-400 hover:text-blue-600"
                >
                  {j.label}
                </a>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ROI Proof Stats */}
      <section className="border-b border-slate-200 bg-slate-50/70 px-5 py-10 sm:px-8">
        <div className="mx-auto max-w-[1280px]">
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-3">
            <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-xs">
              <span className="font-heading text-4xl font-extrabold text-blue-600 sm:text-5xl">3.2x</span>
              <span className="mt-2 block font-heading text-sm font-bold uppercase text-slate-900">
                More Qualified Leads
              </span>
              <p className="mt-1 text-xs text-slate-600">WhatsApp AI capture vs passive contact form drop-off.</p>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-xs">
              <span className="font-heading text-4xl font-extrabold text-slate-900 sm:text-5xl">18+ Hrs</span>
              <span className="mt-2 block font-heading text-sm font-bold uppercase text-slate-900">
                Saved Weekly
              </span>
              <p className="mt-1 text-xs text-slate-600">Automated scheduling, WhatsApp AI replies, and reminder messages.</p>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-xs">
              <span className="font-heading text-4xl font-extrabold text-slate-900 sm:text-5xl">&lt; 6 Wks</span>
              <span className="mt-2 block font-heading text-sm font-bold uppercase text-slate-900">
                Average Payback Time
              </span>
              <p className="mt-1 text-xs text-slate-600">Fast ROI on recovered leads and booked appointments.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Featured All-in-One Growth Suite Spotlight Banner */}
      <section id="suite" className="border-b border-slate-200 bg-white px-5 py-16 sm:px-8 sm:py-20">
        <div className="mx-auto max-w-[1280px]">
          <div className="relative overflow-hidden rounded-3xl border border-slate-800 bg-slate-900 p-8 text-white shadow-xl shadow-blue-900/10 sm:p-12">
            <div className="flex flex-wrap items-center justify-between gap-4">
              <span className="inline-flex items-center gap-2 rounded-full border border-blue-400 bg-blue-500/20 px-3.5 py-1 font-mono text-xs font-semibold text-blue-300">
                <Sparkles className="size-3.5" /> Best-Value Recommended Bundle
              </span>
              <span className="rounded-full border border-white/20 bg-white/10 px-3 py-1 font-mono text-xs uppercase text-slate-300">
                Everything Connected · 1 Team
              </span>
            </div>

            <div className="mt-6 grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-center">
              <div>
                <h2 className="font-heading text-3xl font-extrabold uppercase tracking-tight sm:text-5xl text-white">
                  The Full Growth Suite.
                </h2>
                <p className="mt-4 max-w-xl text-base text-slate-300 leading-relaxed">
                  Your complete customer acquisition machine: High-speed Next.js website + 24/7 WhatsApp AI receptionist + Local SEO domination working together.
                </p>

                <div className="mt-6 grid gap-2.5 sm:grid-cols-2">
                  {[
                    "Custom 10-Page Next.js Web App",
                    "WhatsApp AI Receptionist & Booking Bot",
                    "Google Maps & Review Automation",
                    "Google Calendar & CRM Sync",
                    "Priority 7-Day Build Queue",
                    "90 Days Post-Launch Optimization",
                  ].map((feat) => (
                    <div key={feat} className="flex items-center gap-2 text-xs font-semibold text-slate-200">
                      <Check className="size-4 text-blue-400 shrink-0" />
                      <span>{feat}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="rounded-2xl border border-slate-700 bg-slate-800/80 p-6 text-white shadow-lg">
                <span className="font-mono text-xs font-bold uppercase tracking-[0.14em] text-blue-400">
                  Bundle Launch Deal
                </span>
                <div className="mt-2 flex items-baseline gap-2">
                  <span className="font-heading text-4xl font-extrabold sm:text-5xl text-white">
                    {isINR ? "₹59,999" : "$749"}
                  </span>
                  <span className="font-mono text-base font-bold line-through text-slate-400">
                    {isINR ? "₹1,19,999" : "$1,499"}
                  </span>
                </div>
                <p className="mt-2 text-xs text-slate-300">Complete setup & launch with 100% source code ownership.</p>

                <a
                  href={waLink("Hi Next Scale! I'm interested in the Full Growth Suite bundle (Website + AI Receptionist + Growth). Please share next steps.")}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-full bg-blue-600 hover:bg-blue-700 px-5 py-3 font-mono text-xs font-bold uppercase tracking-wider text-white shadow-md shadow-blue-500/20 transition hover:-translate-y-0.5"
                >
                  Claim Bundle Deal <ArrowRight className="size-4" />
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Section 1: Custom Web Development Packages */}
      <section id="websites" className="border-b border-slate-200 bg-slate-50/50 px-5 py-20 sm:px-8 sm:py-28">
        <div className="mx-auto max-w-[1280px]">
          <div className="mb-14">
            <p className="font-mono text-xs uppercase tracking-[0.2em] text-blue-600 font-semibold">Scoped Web Builds</p>
            <h2 className="mt-2 font-heading text-3xl font-extrabold uppercase tracking-tight sm:text-4xl text-slate-900">
              Custom Next.js Websites
            </h2>
            <p className="mt-4 max-w-xl text-base text-slate-600">
              Handcrafted, mobile-first web platforms with sub-second speeds and built-in conversion architecture.
            </p>
          </div>

          <div className="grid gap-6 md:grid-cols-3">
            {PRICING_WEBSITES.tiers.map((tier) => {
              const displayPrice = isINR ? tier.pricing.inr : tier.pricing.usd;

              return (
                <div
                  key={tier.name}
                  className={`flex flex-col justify-between overflow-hidden rounded-2xl border transition duration-200 ${
                    tier.popular
                      ? "border-blue-600 bg-white shadow-lg shadow-blue-500/5 -translate-y-1"
                      : "border-slate-200 bg-white shadow-xs hover:border-blue-300"
                  }`}
                >
                  <div>
                    {/* Header Stripe */}
                    <div className="flex items-center justify-between border-b border-slate-100 p-6 bg-slate-50/50">
                      <div>
                        <span className="font-mono text-xs font-bold uppercase tracking-[0.14em] text-blue-600">
                          {tier.name} Plan
                        </span>
                        <h3 className="mt-1 font-heading text-2xl font-bold text-slate-900">
                          {tier.name}
                        </h3>
                      </div>
                      {tier.popular && (
                        <span className="rounded-full bg-blue-600 px-2.5 py-0.5 font-mono text-[0.6rem] font-bold uppercase text-white shadow-xs">
                          Popular
                        </span>
                      )}
                    </div>

                    {/* Body */}
                    <div className="p-6">
                      <div className="font-heading text-3xl font-extrabold text-slate-900 sm:text-4xl">
                        {displayPrice}
                      </div>
                      <span className="mt-1 block font-mono text-[0.68rem] font-bold uppercase text-slate-500">
                        {tier.pricing.period}
                      </span>
                      <p className="mt-4 text-xs leading-5 text-slate-600">{tier.description}</p>

                      {/* Feature List */}
                      <div className="mt-6 border-t border-slate-100 pt-5">
                        <p className="font-mono text-[0.68rem] font-bold uppercase tracking-[0.1em] text-slate-900">
                          Features Included:
                        </p>
                        <ul className="mt-3 space-y-2">
                          {tier.features.map((f) => (
                            <li key={f.name} className="flex items-center justify-between text-xs">
                              <span className="flex items-center gap-2">
                                <Check className="size-3.5 text-blue-600 shrink-0" />
                                <span className="font-medium text-slate-700">{f.name}</span>
                              </span>
                              {f.value && (
                                <span className="rounded-md border border-slate-200 bg-slate-50 px-1.5 py-0.5 font-mono text-[0.6rem] font-bold text-slate-700">
                                  {f.value}
                                </span>
                              )}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  </div>

                  <div className="border-t border-slate-100 bg-slate-50/50 p-6">
                    <a
                      href={waLink(
                        `Hi Next Scale! I'm interested in the ${tier.name} Website tier (${displayPrice}). Please share the build timeline.`
                      )}
                      target="_blank"
                      rel="noopener noreferrer"
                      className={`inline-flex w-full items-center justify-center gap-2 rounded-full px-5 min-h-[48px] font-mono text-xs font-bold uppercase tracking-wider transition ${
                        tier.popular
                          ? "bg-blue-600 hover:bg-blue-700 text-white shadow-sm"
                          : "border border-slate-200 bg-white hover:bg-slate-50 text-slate-900"
                      }`}
                    >
                      {tier.name === "Enterprise" ? "Talk Scoping →" : "Build Website →"}
                    </a>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Section 2: 24/7 AI Agents & Retainers */}
      <section id="agents" className="border-b border-slate-200 bg-white px-5 py-20 sm:px-8 sm:py-28">
        <div className="mx-auto max-w-[1280px]">
          <div className="mb-14">
            <p className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-blue-600">Autonomous Retainers</p>
            <h2 className="mt-3 max-w-2xl font-display text-[clamp(2.2rem,5vw,4rem)] font-black leading-[1.05] tracking-tight text-slate-900">
              24/7 WhatsApp AI Agents
            </h2>
            <p className="mt-4 max-w-xl text-base text-slate-600">
              Autonomous customer receptionists trained on your catalog, prices, and booking rules.
            </p>
          </div>

          <div className="grid gap-6 md:grid-cols-3">
            {PRICING_AGENTS.tiers.map((tier, idx) => {
              const currencyObj = isINR ? tier.pricing.inr : tier.pricing.usd;
              const rawPrice = isAnnual ? currencyObj.annual ?? currencyObj.monthly : currencyObj.monthly;
              const isPopular = tier.popular;

              return (
                <div
                  key={tier.name}
                  className={`flex flex-col justify-between overflow-hidden rounded-3xl border transition duration-300 hover:-translate-y-1 ${
                    isPopular
                      ? "border-blue-600 bg-white shadow-xl shadow-blue-500/10"
                      : "border-slate-200 bg-white shadow-sm hover:border-slate-300 hover:shadow-md"
                  }`}
                >
                  <div>
                    {/* Header Stripe */}
                    <div
                      className={`flex items-center justify-between border-b p-6 ${
                        isPopular ? "border-blue-100 bg-blue-50/60" : "border-slate-100 bg-slate-50/80"
                      }`}
                    >
                      <div>
                        <span className="font-mono text-xs font-bold uppercase tracking-wider text-blue-600">
                          AI System
                        </span>
                        <h3 className="mt-1 font-display text-2xl font-bold text-slate-900">
                          {tier.name}
                        </h3>
                      </div>
                      {isPopular && (
                        <span className="rounded-full bg-blue-600 px-3 py-1 text-[0.68rem] font-bold uppercase tracking-wider text-white shadow-sm">
                          Most Popular
                        </span>
                      )}
                    </div>

                    {/* Body */}
                    <div className="p-6">
                      <div className="font-display text-3xl font-black text-slate-900 sm:text-4xl">
                        {String(rawPrice)}
                      </div>
                      <span className="mt-1 block font-mono text-[0.68rem] font-bold uppercase text-slate-500">
                        {currencyObj.setupFee ?? "Monthly Retainer"}
                      </span>
                      <p className="mt-4 text-xs leading-relaxed text-slate-600">{tier.description}</p>

                      {/* Feature List */}
                      <div className="mt-6 border-t border-slate-100 pt-5">
                        <p className="font-mono text-[0.68rem] font-bold uppercase tracking-wider text-slate-400">
                          AI Capabilities:
                        </p>
                        <ul className="mt-3 space-y-2.5">
                          {tier.features.map((f) => (
                            <li key={f.name} className="flex items-center justify-between text-xs">
                              <span className="flex items-center gap-2">
                                <Check className="size-4 text-blue-600 shrink-0" />
                                <span className="font-medium text-slate-800">{f.name}</span>
                              </span>
                              {f.value && (
                                <span className="rounded-md border border-slate-200 bg-slate-100 px-2 py-0.5 font-mono text-[0.65rem] font-bold text-slate-700">
                                  {f.value}
                                </span>
                              )}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  </div>

                  <div className="border-t border-slate-100 bg-slate-50/60 p-6">
                    <a
                      href={waLink(
                        `Hi Next Scale! I'm interested in deploying the ${tier.name} AI Agent plan (${rawPrice}). Can you walk me through the WhatsApp setup?`
                      )}
                      target="_blank"
                      rel="noopener noreferrer"
                      className={`inline-flex w-full items-center justify-center gap-2 rounded-xl px-5 min-h-[48px] text-xs font-bold uppercase tracking-wider transition ${
                        isPopular
                          ? "bg-blue-600 text-white shadow-md shadow-blue-500/20 hover:bg-blue-700"
                          : "border border-slate-200 bg-white text-slate-800 hover:border-blue-600 hover:text-blue-600 hover:bg-blue-50/40"
                      }`}
                    >
                      {tier.name === "Enterprise" ? "Contact Team →" : "Deploy AI Agent →"}
                    </a>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Section 3: Modular Add-ons Grid */}
      <section id="addons" className="border-b border-slate-200 bg-slate-50/50 px-5 py-20 sm:px-8 sm:py-28">
        <div className="mx-auto max-w-[1280px]">
          <div className="mb-14">
            <p className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-blue-600">Modular Add-ons</p>
            <h2 className="mt-3 max-w-2xl font-display text-[clamp(2.2rem,5vw,4rem)] font-black leading-[1.05] tracking-tight text-slate-900">
              Upgrade As You Scale
            </h2>
            <p className="mt-4 max-w-xl text-base text-slate-600">
              Add specialized capabilities to any build without committing to an oversized plan.
            </p>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {PRICING_ADDONS.map((a) => (
              <div
                key={a.name}
                className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-blue-200 hover:shadow-md"
              >
                <div>
                  <h3 className="font-display text-sm font-bold text-slate-900">
                    {a.name}
                  </h3>
                  <span className="font-mono text-xs font-bold text-blue-600">
                    {isINR ? a.inr : a.usd}
                  </span>
                </div>
                <a
                  href={waLink(`Hi Next Scale! I'd like to add ${a.name} to my project.`)}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="rounded-full border border-slate-200 bg-slate-50 px-4 py-2 min-h-[36px] inline-flex items-center font-mono text-[0.68rem] font-bold text-slate-700 transition hover:bg-blue-600 hover:text-white hover:border-blue-600 active:scale-95"
                >
                  + Add
                </a>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Section 4: What Every Plan Includes (Guarantees) */}
      <section className="border-b border-slate-200 bg-white px-5 py-20 sm:px-8 sm:py-28">
        <div className="mx-auto max-w-[1280px]">
          <div className="mb-14 text-center">
            <p className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-blue-600">Our Guarantees</p>
            <h2 className="mt-3 font-display text-[clamp(2.2rem,5vw,4rem)] font-black leading-[1.05] tracking-tight text-slate-900">
              What Every Build Includes
            </h2>
          </div>

          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {GUARANTEES.map((g) => {
              const Icon = g.icon;
              return (
                <div
                  key={g.title}
                  className="rounded-2xl border border-slate-200 bg-slate-50/50 p-6 shadow-sm transition hover:border-blue-200 hover:shadow-md"
                >
                  <div className="flex size-11 items-center justify-center rounded-xl bg-blue-50 border border-blue-100 text-blue-600 shadow-sm">
                    <Icon className="size-5 text-blue-600" />
                  </div>
                  <h3 className="mt-4 font-display text-lg font-bold text-slate-900">
                    {g.title}
                  </h3>
                  <p className="mt-2 text-xs leading-relaxed text-slate-600">{g.desc}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Section 5: FAQ */}
      <section id="faq" className="border-b border-slate-200 bg-slate-50/50 px-5 py-20 sm:px-8 sm:py-28">
        <div className="mx-auto max-w-[1000px]">
          <div className="mb-14">
            <p className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-blue-600">Got Questions?</p>
            <h2 className="mt-3 font-display text-[clamp(2.2rem,5vw,4rem)] font-black leading-[1.05] tracking-tight text-slate-900">
              Frequently Asked Questions
            </h2>
          </div>

          <div className="space-y-4">
            {PRICING_FAQ.map((faq, idx) => (
              <div
                key={idx}
                className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"
              >
                <h3 className="font-display text-base font-bold text-slate-900 sm:text-lg">
                  {faq.q}
                </h3>
                <p className="mt-3 text-xs leading-relaxed text-slate-600 sm:text-sm">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Bottom CTA Banner */}
      <section className="bg-[#0B0F19] px-5 py-20 text-white sm:px-8 sm:py-28">
        <div className="mx-auto max-w-[1000px] text-center">
          <span className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-sky-400">
            Have A Custom Scope In Mind?
          </span>
          <h2 className="mt-4 font-display text-[clamp(2.5rem,6.5vw,5.5rem)] font-black leading-[1.05] tracking-tight text-white">
            Let&apos;s talk <span className="text-blue-400">numbers.</span>
          </h2>
          <p className="mx-auto mt-6 max-w-xl text-base text-slate-300 sm:text-lg">
            Tell us your budget, timeline, and goals on WhatsApp — we will send back a clear scope proposal with zero pushy upsells.
          </p>

          <div className="mt-9 flex flex-col sm:flex-row items-center justify-center gap-4">
            <a
              href={waLink("Hi Next Scale! I'd like a custom pricing proposal for my business.")}
              target="_blank"
              rel="noopener noreferrer"
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-7 min-h-[52px] text-xs font-bold uppercase tracking-wider text-white shadow-lg shadow-blue-500/25 transition hover:-translate-y-0.5 hover:bg-blue-700 active:scale-95"
            >
              <PhoneCall className="size-4" /> Message Us on WhatsApp
            </a>
            <Link
              href="/tools"
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 rounded-xl border border-slate-700 bg-white/5 px-7 min-h-[52px] text-xs font-bold uppercase tracking-wider text-white transition hover:bg-white/10"
            >
              Try Free ROI Calculators →
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
