"use client";

import { useState } from "react";
import Link from "next/link";
import {
  Calculator,
  TrendingUp,
  MessageCircle,
  Clock,
  ShieldCheck,
  Zap,
  ArrowRight,
  DollarSign,
  Users,
  CheckCircle2,
} from "lucide-react";
import { PageHero } from "@/components/ui/page-hero";
import { JsonLd } from "@/components/seo/json-ld";
import { breadcrumbSchema } from "@/lib/seo";
import { SITE, waLink } from "@/lib/site";

export default function AiRoiCalculatorPage() {
  const [monthlyLeads, setMonthlyLeads] = useState(250);
  const [staffCount, setStaffCount] = useState(2);
  const [staffSalary, setStaffSalary] = useState(20000);
  const [dealValue, setDealValue] = useState(2500);

  // Calculations based on 2026 empirical benchmark data
  const monthlyManualStaffCost = staffCount * staffSalary;
  const staffHoursSavedMonthly = staffCount * 60; // 15h/week * 4 weeks
  const afterHoursLeadsRecovered = Math.round(monthlyLeads * 0.4 * 0.35); // 40% after hours * 35% converted by instant AI
  const extraMonthlyRevenue = afterHoursLeadsRecovered * dealValue;
  const aiCost = 24999; // Standard starter agent cost
  const netMonthlyGain = extraMonthlyRevenue + (monthlyManualStaffCost * 0.4) - aiCost;
  const netAnnualGain = netMonthlyGain * 12;

  const toolSchema = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: "AI Automation ROI Calculator India",
    url: `${SITE.url}/tools/ai-roi-calculator`,
    applicationCategory: "BusinessApplication",
    operatingSystem: "Web",
    browserRequirements: "Requires JavaScript",
    description: "Calculate return on investment, staff hours reclaimed, and revenue recovered from deploying 24/7 WhatsApp AI receptionists.",
    author: {
      "@type": "Person",
      "@id": `${SITE.url}/#founder`,
      name: SITE.founder,
      url: `${SITE.url}/about/abhisek-pani`,
    },
    publisher: {
      "@type": "Organization",
      "@id": `${SITE.url}/#organization`,
      name: SITE.name,
      url: SITE.url,
    },
  };

  return (
    <div className="min-h-screen bg-[#FAF3E5] text-[#141414] pb-24">
      <JsonLd
        schema={[
          toolSchema,
          breadcrumbSchema([
            { name: "Home", path: "/" },
            { name: "Tools", path: "/tools" },
            { name: "AI ROI Calculator", path: "/tools/ai-roi-calculator" },
          ]),
        ]}
      />

      <PageHero
        kicker="Free Financial Modeling Tool"
        title={
          <>
            WhatsApp AI <span className="text-[#FF4D00]">ROI Calculator</span>
          </>
        }
        description="Estimate direct cost savings, administrative hours reclaimed, and new consultation revenue generated by automating customer booking flows 24/7."
      />

      <main className="mx-auto max-w-5xl px-4 py-8 sm:py-14">
        <div className="grid gap-8 lg:grid-cols-[3fr_2fr]">
          {/* Inputs */}
          <div className="rounded-3xl border-2 border-[#141414] bg-[#FFFCF5] p-6 shadow-[6px_6px_0px_#141414] sm:p-8">
            <h2 className="font-heading text-xl font-black text-[#141414] mb-6">
              Enter Your Operational Metrics
            </h2>

            <div className="space-y-6">
              {/* Monthly Leads */}
              <div>
                <div className="flex justify-between items-center mb-2">
                  <label className="text-xs font-black uppercase tracking-wider text-[#5B5146]">
                    Monthly Inquiries / WhatsApp Leads
                  </label>
                  <span className="font-mono text-sm font-black text-[#FF4D00]">
                    {monthlyLeads} Leads / mo
                  </span>
                </div>
                <input
                  type="range"
                  min="50"
                  max="2000"
                  step="25"
                  value={monthlyLeads}
                  onChange={(e) => setMonthlyLeads(Number(e.target.value))}
                  className="w-full accent-[#FF4D00] cursor-pointer"
                />
              </div>

              {/* Staff Count */}
              <div>
                <div className="flex justify-between items-center mb-2">
                  <label className="text-xs font-black uppercase tracking-wider text-[#5B5146]">
                    Front-Desk / Reception Staff Count
                  </label>
                  <span className="font-mono text-sm font-black text-[#FF4D00]">
                    {staffCount} Staff Members
                  </span>
                </div>
                <input
                  type="range"
                  min="1"
                  max="10"
                  step="1"
                  value={staffCount}
                  onChange={(e) => setStaffCount(Number(e.target.value))}
                  className="w-full accent-[#FF4D00] cursor-pointer"
                />
              </div>

              {/* Staff Salary */}
              <div>
                <div className="flex justify-between items-center mb-2">
                  <label className="text-xs font-black uppercase tracking-wider text-[#5B5146]">
                    Average Monthly Salary per Staff
                  </label>
                  <span className="font-mono text-sm font-black text-[#FF4D00]">
                    ₹{staffSalary.toLocaleString("en-IN")}/mo
                  </span>
                </div>
                <input
                  type="range"
                  min="10000"
                  max="60000"
                  step="2000"
                  value={staffSalary}
                  onChange={(e) => setStaffSalary(Number(e.target.value))}
                  className="w-full accent-[#FF4D00] cursor-pointer"
                />
              </div>

              {/* Average Deal / Consultation Value */}
              <div>
                <div className="flex justify-between items-center mb-2">
                  <label className="text-xs font-black uppercase tracking-wider text-[#5B5146]">
                    Average Transaction / Consultation Value
                  </label>
                  <span className="font-mono text-sm font-black text-[#FF4D00]">
                    ₹{dealValue.toLocaleString("en-IN")}
                  </span>
                </div>
                <input
                  type="range"
                  min="500"
                  max="50000"
                  step="500"
                  value={dealValue}
                  onChange={(e) => setDealValue(Number(e.target.value))}
                  className="w-full accent-[#FF4D00] cursor-pointer"
                />
              </div>
            </div>
          </div>

          {/* Results Display */}
          <div className="flex flex-col gap-6">
            <div className="rounded-3xl border-2 border-[#141414] bg-[#FFFCF5] p-6 shadow-[6px_6px_0px_#141414] sm:p-8">
              <span className="text-xs font-black uppercase tracking-wider text-[#0F6838]">
                Estimated Financial Upside
              </span>

              <div className="mt-4">
                <span className="text-xs font-bold text-[#5B5146]">Net Estimated Monthly Gain</span>
                <div className="font-heading text-4xl font-black text-[#141414] sm:text-5xl text-[#0F6838]">
                  +₹{Math.max(0, netMonthlyGain).toLocaleString("en-IN")}
                </div>
                <p className="text-xs text-[#5B5146] mt-1">
                  Annualized Opportunity: <strong className="text-[#141414]">₹{Math.max(0, netAnnualGain).toLocaleString("en-IN")} / year</strong>
                </p>
              </div>

              <div className="mt-6 divide-y divide-[#141414]/10 rounded-2xl border-2 border-[#141414] bg-[#FAF3E5] p-4 text-xs font-bold space-y-2">
                <div className="flex items-center justify-between pt-1">
                  <span className="text-[#5B5146]">After-Hours Leads Recovered:</span>
                  <span className="text-[#141414] font-black">+{afterHoursLeadsRecovered} bookings / mo</span>
                </div>
                <div className="flex items-center justify-between pt-2">
                  <span className="text-[#5B5146]">Staff Hours Reclaimed:</span>
                  <span className="text-[#141414] font-black">+{staffHoursSavedMonthly} hours / mo</span>
                </div>
                <div className="flex items-center justify-between pt-2">
                  <span className="text-[#5B5146]">Estimated Payback Period:</span>
                  <span className="text-[#0F6838] font-black">Under 18 Days</span>
                </div>
              </div>

              <a
                href={waLink(
                  `Hi Abhisek! I modeled my AI ROI (+₹${Math.max(0, netMonthlyGain).toLocaleString("en-IN")}/mo, ${monthlyLeads} leads). I would like to deploy an agent for my business.`
                )}
                target="_blank"
                rel="noopener noreferrer"
                className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl border-2 border-[#141414] bg-[#25D366] py-3.5 text-xs font-black text-[#141414] shadow-[3px_3px_0px_#141414] transition-all hover:bg-[#1ebd5a]"
              >
                <MessageCircle className="size-4" />
                Deploy AI Agent on WhatsApp
              </a>
            </div>

            {/* Research Report Card */}
            <div className="rounded-2xl border-2 border-[#141414] bg-[#FAF3E5] p-5 shadow-[3px_3px_0px_#141414]">
              <h3 className="font-heading text-xs font-black uppercase tracking-wider text-[#141414] mb-1">
                Read the India AI Adoption Report 2026
              </h3>
              <p className="text-xs text-[#5B5146] mb-3">
                See verified inquiry deflection data from 150+ clinics and SMBs across India.
              </p>
              <Link
                href="/resources/research/india-ai-adoption-report-2026"
                className="inline-flex items-center gap-1 text-xs font-black text-[#FF4D00] hover:underline"
              >
                <span>Read Full Research Report</span>
                <ArrowRight className="size-3" />
              </Link>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
